### ISSUE TITLE
Redirect sign-in teacher

### ISSUE THREAD

**Issue by TheMindset** [thp-next-projet-2/meet_my_class#21]
**WHY**

Improve UX 

**TODO**

* [ ] Send links for confirm registration
* [ ] Click on links and redirect to home page
* [ ] flash success : "You’re now registered user, and email confirmation has been sent to you” 

**MUST HAVE**

* [ ] email for registration and flash success
