### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by TheMindset** [thp-next-projet-2/meet_my_class#22]
**WHY**

Use this repo easily

**TODO**

* [x] Show how use this repo
* [x] what to handle on terminal make it work
* [x] how launch this in developement and production

**MUST HAVE**

 * [x]  A complete documentary
