### ISSUE TITLE
Add cypress (related : #2)

### ISSUE THREAD

**Issue by TheMindset** [thp-next-projet-2/meet_my_class#23]
**WHY**

Make integration test

**TODO**

* [ ] add gem "cypress"
* [ ] config "cypress"
* [ ] add "cypress" in CircleCi

**MUST HAVE**

* [ ] Cypress work in development and production
