### ISSUE TITLE
Redirect sign-in Student

### ISSUE THREAD

**Issue by NIcoZF** [thp-next-projet-2/meet_my_class#5]
**WHY**

Improve UX 

**TODO**

* [ ] Send links for confirm registration
* [ ] Click on links and redirect to home page
* [ ] flash success : "You’re now registered user, and email confirmation has been sent to you” 

**MUST HAVE**

* [ ] email for registration and flash success
